{
  description = "R development environment with radian (generated by rix)";

  inputs = {
    nixpkgs.url = "{{NIXPKGS_URL}}";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Import the package definitions generated by rix
        rixEnv = import ./.rixpackages.nix pkgs;

        # Radian with all R packages
        radian-with-packages = pkgs.radianWrapper.override {
          packages = [ rixEnv.rpkgs ];
        };

        # R for fallback
        r-with-packages = pkgs.rWrapper.override {
          packages = [ rixEnv.rpkgs ];
        };

      in {
        # Packages
        packages = {
          default = radian-with-packages;
          radian = radian-with-packages;
          r = r-with-packages;
        };

        # Development shells
        devShells = {
          # Default: radian for interactive use
          default = pkgs.mkShell {
            buildInputs = [ radian-with-packages ] ++ rixEnv.system_packages;
            inherit (rixEnv.shell) LOCALE_ARCHIVE LANG LC_ALL LC_TIME;
            inherit (rixEnv.shell) LC_MONETARY LC_PAPER LC_MEASUREMENT;
          };

          # R-only shell (no radian)
          r = rixEnv.shell;
        };

        # Apps
        apps = {
          default = {
            type = "app";
            program = "${radian-with-packages}/bin/radian";
          };
          radian = {
            type = "app";
            program = "${radian-with-packages}/bin/radian";
          };
          r = {
            type = "app";
            program = "${r-with-packages}/bin/R";
          };
        };
      });
}
