{
  description = "R development environment with OCI container support (generated by rix)";

  nixConfig = {
    extra-substituters = [
      "https://rstats-on-nix.cachix.org"
    ];
    extra-trusted-public-keys = [
      "rstats-on-nix.cachix.org-1:ylMXt/GRAA2NJ3PvfHYjbgS7XyXq8kLl3fDbvmqDGE8="
    ];
  };

  inputs = {
    nixpkgs.url = "https://github.com/rstats-on-nix/nixpkgs/archive/2023-10-30.tar.gz";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Import the package definitions generated by rix
        rixEnv = import ./.rixpackages.nix pkgs;

        # R with all packages
        r-with-packages = pkgs.rWrapper.override {
          packages = [ rixEnv.rpkgs ];
        };

        # Create a layered Docker image
        dockerImage = pkgs.dockerTools.buildLayeredImage {
          name = "r-env";
          tag = "latest";

          contents = [
            r-with-packages
            pkgs.R
            pkgs.bash
            pkgs.coreutils
          ] ++ rixEnv.system_packages;

          config = {
            Env = [
              "LC_ALL=en_US.UTF-8"
              "LANG=en_US.UTF-8"
            ];
            Entrypoint = [ "${r-with-packages}/bin/R" ];
            WorkingDir = "/data";
          };

          # Max layers to use (Docker has limit of 127)
          maxLayers = 100;
        };

        # Create a smaller streamLayeredImage variant
        dockerImageStream = pkgs.dockerTools.streamLayeredImage {
          name = "r-env";
          tag = "latest";

          contents = [
            r-with-packages
            pkgs.R
            pkgs.bash
            pkgs.coreutils
          ] ++ rixEnv.system_packages;

          config = {
            Env = [
              "LC_ALL=en_US.UTF-8"
              "LANG=en_US.UTF-8"
            ];
            Entrypoint = [ "${r-with-packages}/bin/R" ];
            WorkingDir = "/data";
          };

          maxLayers = 100;
        };

      in {
        # Packages
        packages = {
          default = r-with-packages;
          r = r-with-packages;

          # Docker/OCI container images
          docker = dockerImage;
          container = dockerImage;
          docker-stream = dockerImageStream;
        };

        # Development shell
        devShells.default = rixEnv.shell;

        # Apps
        apps = {
          default = {
            type = "app";
            program = "${r-with-packages}/bin/R";
          };
          r = {
            type = "app";
            program = "${r-with-packages}/bin/R";
          };
        };
      });
}
