{
  description = "R development environment with Positron (generated by rix)";

  nixConfig = {
    extra-substituters = [
      "https://rstats-on-nix.cachix.org"
    ];
    extra-trusted-public-keys = [
      "rstats-on-nix.cachix.org-1:ylMXt/GRAA2NJ3PvfHYjbgS7XyXq8kLl3fDbvmqDGE8="
    ];
  };

  inputs = {
    nixpkgs.url = "https://github.com/rstats-on-nix/nixpkgs/archive/2023-10-30.tar.gz";
    flake-utils.url = "github:numtide/flake-utils";
  };

  nixConfig = {
    allowUnfree = true;
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Import the package definitions generated by rix
        rixEnv = import ./.rixpackages.nix pkgs;

        # R with all packages
        r-with-packages = pkgs.rWrapper.override {
          packages = [ rixEnv.rpkgs ];
        };

      in {
        # Packages
        packages = {
          default = r-with-packages;
          r = r-with-packages;
        };

        # Development shell with Positron
        devShells = {
          default = pkgs.mkShell {
            buildInputs = [
              r-with-packages
              pkgs.positron-bin
            ] ++ rixEnv.system_packages;
            inherit (rixEnv.shell) LOCALE_ARCHIVE LANG LC_ALL LC_TIME;
            inherit (rixEnv.shell) LC_MONETARY LC_PAPER LC_MEASUREMENT;
          };

          # R-only shell
          r = rixEnv.shell;

          # Positron only
          positron = pkgs.mkShell {
            buildInputs = [ pkgs.positron-bin ];
          };
        };

        # Apps
        apps = {
          default = {
            type = "app";
            program = "${pkgs.positron-bin}/bin/positron";
          };
          positron = {
            type = "app";
            program = "${pkgs.positron-bin}/bin/positron";
          };
          r = {
            type = "app";
            program = "${r-with-packages}/bin/R";
          };
        };
      });
}
