{
  description = "R development environment with RStudio (generated by rix)";

  nixConfig = {
    extra-substituters = [
      "https://rstats-on-nix.cachix.org"
    ];
    extra-trusted-public-keys = [
      "rstats-on-nix.cachix.org-1:ylMXt/GRAA2NJ3PvfHYjbgS7XyXq8kLl3fDbvmqDGE8="
    ];
  };

  inputs = {
    nixpkgs.url = "https://github.com/rstats-on-nix/nixpkgs/archive/2023-10-30.tar.gz";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Import the package definitions generated by rix
        rixEnv = import ./.rixpackages.nix pkgs;

        # RStudio with all R packages
        rstudio-with-packages = pkgs.rstudioWrapper.override {
          packages = [ rixEnv.rpkgs rixEnv.git_archive_pkgs rixEnv.local_r_pkgs ];
        };

        # R for fallback
        r-with-packages = pkgs.rWrapper.override {
          packages = [ rixEnv.rpkgs rixEnv.git_archive_pkgs rixEnv.local_r_pkgs ];
        };

      in {
        # Packages
        packages = {
          default = rstudio-with-packages;
          rstudio = rstudio-with-packages;
          r = r-with-packages;
        };

        # Development shells
        devShells = {
          # Default: shell with RStudio
          default = pkgs.mkShell {
            buildInputs = [ rstudio-with-packages ] ++ rixEnv.system_packages;
            inherit (rixEnv.shell) LOCALE_ARCHIVE LANG LC_ALL LC_TIME;
            inherit (rixEnv.shell) LC_MONETARY LC_PAPER LC_MEASUREMENT;
          };

          # R-only shell
          r = rixEnv.shell;
        };

        # Apps
        apps = {
          default = {
            type = "app";
            program = "${rstudio-with-packages}/bin/rstudio";
          };
          rstudio = {
            type = "app";
            program = "${rstudio-with-packages}/bin/rstudio";
          };
          r = {
            type = "app";
            program = "${r-with-packages}/bin/R";
          };
        };
      });
}
