# This file was generated by the {rix} R package v0.7.0 on 2024-05-22
# with following call:
# >rix(r_ver = "https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/r-daily.tar.gz",
#  > r_pkgs = c("devtools",
#  > "diffviewer",
#  > "fledge",
#  > "codetools",
#  > "jsonlite",
#  > "httr",
#  > "sys",
#  > "testthat",
#  > "knitr",
#  > "rmarkdown"),
#  > system_pkgs = c("R",
#  > "glibcLocalesUtf8",
#  > "pandoc",
#  > "nix"),
#  > tex_pkgs = "scheme-small",
#  > ide = "radian",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = FALSE,
#  > shell_hook = NULL)
# It uses nixpkgs' revision refs/heads/r-daily for reproducibility purposes
# which will install R version bleeding_edge
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/r-daily.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) devtools diffviewer fledge codetools jsonlite httr sys testthat knitr rmarkdown;
};
  tex = (pkgs.texlive.combine {
  inherit (pkgs.texlive) scheme-small;
});
 system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocalesUtf8 pandoc nix;
};
 wrapped_pkgs = pkgs.radianWrapper.override {
  packages = [  rpkgs ];
};
 in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [  rpkgs tex system_packages wrapped_pkgs ];
      
  }
