# This file was generated by the {rix} R package v0.11.0 on 2024-09-20
# with following call:
# >rix(r_ver = "658e7223191d2598641d50ee4e898126768fe847",
#  > r_pkgs = c("devtools",
#  > "diffviewer",
#  > "fledge",
#  > "lintr",
#  > "styler",
#  > "codetools",
#  > "jsonlite",
#  > "httr",
#  > "sys",
#  > "testthat",
#  > "knitr",
#  > "rmarkdown",
#  > "rhub"),
#  > system_pkgs = c("R",
#  > "glibcLocalesUtf8",
#  > "pandoc",
#  > "nix"),
#  > tex_pkgs = c("inconsolata"),
#  > ide = "other",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = FALSE,
#  > shell_hook = NULL)
# It uses nixpkgs' revision 658e7223191d2598641d50ee4e898126768fe847 for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/658e7223191d2598641d50ee4e898126768fe847.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      codetools
      devtools
      diffviewer
      fledge
      httr
      jsonlite
      knitr
      lintr
      rhub
      rmarkdown
      styler
      sys
      testthat;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      inconsolata;
  });
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      glibcLocalesUtf8
      nix
      pandoc
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs tex system_packages   ];
  
}
