# This file was generated by the {rix} R package v0.11.0 on 2024-09-16
# with following call:
# >rix(r_ver = "bleeding_edge",
#  > r_pkgs = c("devtools",
#  > "diffviewer",
#  > "fledge",
#  > "lintr",
#  > "styler",
#  > "codetools",
#  > "jsonlite",
#  > "httr",
#  > "sys",
#  > "testthat",
#  > "knitr",
#  > "rmarkdown",
#  > "rhub",
#  > "docopt",
#  > "precommit"),
#  > system_pkgs = c("R",
#  > "glibcLocalesUtf8",
#  > "pandoc",
#  > "nix"),
#  > tex_pkgs = "scheme-small",
#  > ide = "other",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = FALSE,
#  > shell_hook = NULL)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides bleeding
# edge packages and R.
# Only use bleeding edge packages if absolutely needed!
# Read more on https://ropensci.github.io/rix/articles/z-bleeding_edge.html
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/r-daily.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      codetools
      devtools
      diffviewer
      docopt
      fledge
      httr
      jsonlite
      knitr
      lintr
      precommit
      rhub
      rmarkdown
      styler
      sys
      testthat;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small;
  });
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      glibcLocalesUtf8
      nix
      pandoc
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs tex system_packages   ];
  
}
