# This file was generated by the {rix} R package v0.1.1 on Mon Aug 14 00:01:47 2023
# with following call:
# >rix(r_ver = "8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8",
#  > r_pkgs = NULL,
#  > other_pkgs = NULL,
#  > git_pkgs = list(package_name = "rix",
#  > repo_url = "https://github.com/b-rodrigues/rix/",
#  > branch_name = "master",
#  > commit = "da581f90273cb1ccfedbe18808097bf33b84d63c"),
#  > ide = "other",
#  > project_path = "inst/extdata",
#  > overwrite = TRUE)
# It uses nixpkgs' revision 8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8 for reproducibility purposes
# which will install R as it was as of nixpkgs revision: 8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8
# Report any issues to https://github.com/b-rodrigues/rix
let
  pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8.tar.gz") {};
 git_archive_pkgs = [(pkgs.rPackages.buildRPackage {
    name = "housing";
    src = pkgs.fetchgit {
      url = "https://github.com/rap4all/housing/";
      branchName = "fusen";
      rev = "1c860959310b80e67c41f7bbdc3e84cef00df18e";
      sha256 = "sha256-s4KGtfKQ7hL0sfDhGb4BpBpspfefBN6hf+XlslqyEn4=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) dplyr ggplot2 janitor purrr readxl rlang rvest stringr tidyr;
    };
  })
(pkgs.rPackages.buildRPackage {
    name = "fusen";
    src = pkgs.fetchgit {
      url = "https://github.com/ThinkR-open/fusen";
      branchName = "main";
      rev = "d617172447d2947efb20ad6a4463742b8a5d79dc";
      sha256 = "sha256-TOHA1ymLUSgZMYIA1a2yvuv0799svaDOl3zOhNRxcmw=";
    };
    propagatedBuildInputs = builtins.attrValues {
      inherit (pkgs.rPackages) attachment cli desc devtools glue here magrittr parsermd roxygen2 stringi tibble tidyr usethis yaml;
    };
  })];
  rpkgs = builtins.attrValues {
      inherit (pkgs.rPackages) dplyr janitor quarto;
  };
  system_packages = builtins.attrValues {
      inherit (pkgs) R quarto;
  };
in
  pkgs.mkShell {
   buildInputs = 
     system_packages ++
     rpkgs ++
     git_archive_pkgs;
  shellHook = "R --vanilla";
  }