---
title: "b2 - Setting up and using rix on macOS"
output: html_document
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: 80
---

*This vignette will discuss macOS-specific topics. If you're not using macOS, you
can ignore this vignette, and read the 
`vignette("b1-setting-up-and-using-rix-on-linux-and-windows")`
vignette instead.*

## Introduction

When it comes to Nix, there are really only two supported operating systems: macOS
and Linux distributions. Windows is "supported" because it is actually running
Linux thanks to WSL2. In practice this means that Linux distributions and Windows
can be considered one system, and macOS another, separate, system, with its own
idiosyncracies. This vignette details these.

## Installing Nix

You can use `{rix}` to generate Nix expressions even if you don't have Nix
installed on your system, but obviously, you need to install Nix if you actually
want to build the defined development environment and use them. Installing (and
uninstalling) Nix is quite simple, thanks to the installer from [Determinate
Systems](https://determinate.systems/posts/determinate-nix-installer), a company
that provides services and tools built on Nix. Simply open a terminal and run
the following line:

```{sh, eval=FALSE}
curl --proto '=https' --tlsv1.2 -sSf \
    -L https://install.determinate.systems/nix | \
     sh -s -- install
```

Once you have Nix installed, you can build the expressions you generate with
`{rix}`!

## What if you don't have R already installed?

If you have successfully installed Nix, but don't have yet R installed on your
system, you could install R as you would usually do on your operating system,
and then install the `{rix}` package, and from there, generated project-specific
expressions and build them. But you could also install R using Nix. Running the
following line in a terminal will drop you in an interactive R session that you
can use to start generating expressions:

```
nix-shell --expr "$(curl -sl https://raw.githubusercontent.com/b-rodrigues/rix/master/inst/extdata/default.nix)"
```

This should immediately start an R session inside your terminal. You can now run
something like this:

```
rix(r_ver = "latest",
    r_pkgs = c("dplyr", "ggplot2"),
    system_pkgs = NULL,
    git_pkgs = NULL,
    ide = "other",
    project_path = ".",
    overwrite = TRUE)
```

to generate a `default.nix`, and then use that file to generate an environment
with R, `{dplyr}` and `{ggplot2}`. If you need to add packages for your project,
rerun the command above, but add the needed packages to `r_pkgs`. This is
detailled in the vignette
`vignette("d1-installing-r-packages-in-a-nix-environment")` and
`vignette("d2-installing-system-tools-and-texlive-packages-in-a-nix-environment")`.

## Generating expressions

Once you have R installed, either through the usual installer for your operating
system, or through Nix as explained previously, you can now start building
project-specific development environments.

On macOS, generating expressions works just like on Linux and Windows. Start an
R session, and install `{rix}` if that's not already done. Because `{rix}` is
not yet on CRAN, the easiest way is to install it from its r-universe:

```{r, eval=FALSE}
install.packages("rix", repos = c("https://b-rodrigues.r-universe.dev",
  "https://cloud.r-project.org"))
```

You can then use the `{rix}` package to generate expressions. Consult the
next vignette `vignette("c-using-rix-to-build-project-specific-environments")` to learn more.

## More macOS specificities

### Shared libraries issue

When using environments built with Nix on macOS, you might get error messages
refering to "shared libraries", which indicate that your user library of R
packages is interfering with the project-specific Nix environment. In this case,
you might want to set up a project-specific `.Rprofile` using `rix::rix_init()`.
This function generates an `.Rprofile` file on the root of your project and
ensures that the Nix environment only loads R packages from its own
project-specific library. This should solve the issue.

### RStudio and other development interfaces on macOS

As of writing, RStudio cannot be installed through `nixpkgs` for macOS, and if
you wish to use RStudio with a Nix environment, you have to install it through
`nixpkgs`. This means that it is impossible to use RStudio and a Nix environment
on macOS. When you try to generate an expression with `ide =
"rstudio"` on macOS, this will raise a warning. Here are the options you have:

- ignore the warning, because the environment will be built on a Linux
  distribution (even though you generated the expression on macOS) and used on a
  Linux distribution;
- change the `ide =` argument to either `"other"` or `"code"`. Use `"code"` if
  you want to use VS Code and `"other"` for any other editor, like Vim or Emacs.
  These other editors don't need to be installed through `nixpkgs` to use Nix environments,
  unlike RStudio;
- if you're working on a pipeline with the `{targets}` package, you could run it
  on Github Actions. This means you could work on the code on RStudio outside
  of the Nix environment, as the code will only be executed on Github Actions runners. See this
  vignette `vignette("z-advanced-topic-reproducible-analytical-pipelines-with-nix")` for further details;
- work on your project as usual, using your usual installation of R and RStudio,
  but generate a `default.nix` at the end with `ide = "other"` with the right
  version of R for reproducibility purposes;
- use subshells to execute only the code you need to run in a specific
  environment. See this vignette `vignette("z-advanced-topic-running-r-or-shell-code-in-nix-from-r")`;

- help us package RStudio for macOS on `nixpgs`. See
  [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/rstudio/default.nix),
  the Nix expression for RStudio.
  
We recommend you continue with the next vignette before tackling the more advanced
topics listed above: `vignette("c-using-rix-to-build-project-specific-environments")`.
