---
title: "Run targets pipelines on Github Actions"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

The function below copies a Github actions workflow file into the
`.github/workflows/run-pipeline.yaml`:

```{r function-nix_github_actions}
#' tar_nix_ga
#' @return Nothing, copies file to a diretory.
#'
tar_nix_ga <- function(){
  # Add an empty .gitignore file if there isn’t any

  if(file.exists(".gitignore")){
    NULL
  } else {
    file.create(".gitignore")
  }

  dir.create(".github/workflows", recursive = TRUE)
  source <- system.file(
    file.path("extdata", "run-pipeline.yaml"),
    package = "rix",
    mustWork = TRUE
  )
  file.copy(source, path, overwrite = TRUE)
  invisible()
}
```

Be sure to give Github Actions workflows read and write permissions.
