---
title: "rix"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

This next function returns a `default.nix` file that can be used to build a
reproducible environment. This function takes an R version as an input (the
correct Nix revision is found using `find_rev()`), a list of R packages, and
whether the user wants to work with RStudio or not in that environment. If
you use another IDE, you can leave the "ide" argument blank:

```{r function-rix}
#' rix Generates a Nix expression that builds a reproducible development environment
#' @return Nothing, this function only has the side-effect of writing a file
#'   called "default.nix" in the working directory. This file contains the
#'   expression to build a reproducible environment using the Nix package
#'   manager.
#' @param r_ver Character, defaults to "latest". The required R version, for example "4.0.0".
#'   You can check which R versions are available using `available_r`.
#'   For reproducibility purposes, you can also provide a nixpkgs revision directly.
#' @param r_pkgs Vector of characters. List the required R packages for your
#'   analysis here.
#' @param system_pkgs Vector of characters. List further software you wish to install that
#'   are not R packages such as command line applications for example. You can look for
#'   available software on the NixOS website \url{https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=}
#' @param git_pkgs List. A list of packages to install from Git. See details for more information.
#' @param tex_pkgs Vector of characters. A set of tex packages to install. Use this if you need to compile `.tex` documents, or build PDF documents using Quarto. If you don't know which package to add, start by adding "amsmath". See the Vignette "Authoring LaTeX documents" for more details.
#' @param ide Character, defaults to "other". If you wish to use RStudio to work
#'   interactively use "rstudio" or "code" for Visual Studio Code. For other editors,
#'   use "other". This has been tested with RStudio, VS Code and Emacs. If other
#'   editors don't work, please open an issue.
#' @param project_path Character, defaults to the current working directory. 
#'   Where to write `default.nix`, for example "/home/path/to/project".
#'   The file will thus be written to the file 
#'   "/home/path/to/project/default.nix".
#' @param overwrite Logical, defaults to FALSE. If TRUE, overwrite the `default.nix`
#'   file in the specified path.
#' @param print Logical, defaults to FALSE. If TRUE, print `default.nix` to console.
#' @param shell_hook Character of length 1, defaults to `NULL`. Commands added
#'   to the `shellHook` variable executed when the Nix shell starts. So
#'   by default, using `nix-shell default.nix` (or path with `shell.nix`) will 
#'   start a specific program, possibly with flags (separated by space), and/or
#'   do shell actions. You can for example use `shell_hook = R`, if you want to
#'   directly enter the declared Nix R session.
#' @details This function will write a `default.nix` in the chosen path. Using
#'   the Nix package manager, it is then possible to build a reproducible
#'   development environment using the `nix-build` command in the path. This
#'   environment will contain the chosen version of R and packages, and will not
#'   interfere with any other installed version (via Nix or not) on your
#'   machine. Every dependency, including both R package dependencies but also
#'   system dependencies like compilers will get installed as well in that
#'   environment. If you use RStudio for interactive work, then set the
#'   `rstudio` parameter to `TRUE`. If you use another IDE (for example Emacs or
#'   Visual Studio Code), you do not need to add it to the `default.nix` file,
#'   you can simply use the version that is installed on your computer. Once you built
#'   the environment using `nix-build`, you can drop into an interactive session
#'   using `nix-shell`. See the "Building reproducible development environments with rix"
#'   vignette for detailled instructions.
#'   Packages to install from Github must be provided in a list of 4 elements:
#'   "package_name", "repo_url", "branch_name" and "commit".
#'   This argument can also be a list of lists of these 4 elements. It is also possible to install old versions
#'   of packages by specifying a version. For example, to install the latest
#'   version of `{AER}` but an old version of `{ggplot2}`, you could
#'   write: `r_pkgs = c("AER", "ggplot2@2.2.1")`. Note
#'   however that doing this could result in dependency hell, because an older
#'   version of a package might need older versions of its dependencies, but other
#'   packages might need more recent versions of the same dependencies. If instead you
#'   want to use an environment as it would have looked at the time of `{ggplot2}`'s
#'   version 2.2.1 release, then use the Nix revision closest to that date, by setting
#'   `r_ver = "3.1.0"`, which was the version of R current at the time. This
#'   ensures that Nix builds a completely coherent environment.
#'   By default, the nix shell will be configured with `"en_US.UTF-8"` for the
#'   relevant locale variables (`LANG`, `LC_ALL`, `LC_TIME`, `LC_MONETARY`,
#'   `LC_PAPER`, `LC_MEASUREMENT`). This is done to ensure locale
#'   reproducibility by default in Nix environments created with `rix()`.
#'   If there are good reasons to not stick to the default, you can set your
#'   preferred locale variables via 
#'   `options(rix.nix_locale_variables = list(LANG = "de_CH.UTF-8", <...>)`
#'   and the aforementioned locale variable names.
#' @export
#' @examples
#' \dontrun{
#' # Build an environment with the latest version of R
#' # and the dplyr and ggplot2 packages
#' rix(r_ver = "latest",
#'     r_pkgs = c("dplyr", "ggplot2"),
#'     system_pkgs = NULL,
#'     git_pkgs = NULL,
#'     ide = "code",
#'     project_path = path_default_nix,
#'     overwrite = TRUE,
#'     print = TRUE,
#'     shell_hook = NULL)
#' }
rix <- function(r_ver = "latest",
                r_pkgs = NULL,
                system_pkgs = NULL,
                git_pkgs = NULL,
                tex_pkgs = NULL,
                ide = "other",
                project_path = ".",
                overwrite = FALSE,
                print = FALSE,
                shell_hook = NULL){

  stopifnot("'ide' has to be one of 'other', 'rstudio' or 'code'" = (ide %in% c("other", "rstudio", "code")))

  if(Sys.info()["sysname"] == "Darwin" & ide == "rstudio"){
    warning(
      "Your detected operating system is macOS, and you chose
'rstudio' as the IDE. Please note that 'rstudio' is not
available through 'nixpkgs' for macOS, so the expression you
generated will not build on macOS. If you wish to build this
expression on macOS, change the 'ide =' argument to either
'code' or 'other'. Please refer to the macOS-specific vignette
https://b-rodrigues.github.io/rix/articles/b2-setting-up-and-using-rix-on-macos.html
for more details.")
  }

  project_path <- if(project_path == "."){
     "default.nix"
  } else {
    paste0(project_path, "/default.nix")
  }

  # Generate the correct text for the header depending on wether
  # an R version or a Nix revision is supplied to `r_ver`
  if(nchar(r_ver) > 20){
    r_ver_text <- paste0("as it was as of nixpkgs revision: ", r_ver)
  } else {
    r_ver_text <- paste0("version ", r_ver)
  }

  # Find the Nix revision to use
  nix_revision <- find_rev(r_ver)

  project_path <- file.path(project_path)

  rix_call <- match.call()

  generate_rix_call <- function(rix_call, nix_revision){

    rix_call$r_ver <- nix_revision

    rix_call <- paste0("# >", deparse1(rix_call))

    gsub(",", ",\n#  >", rix_call)
  }

  # Get the rix version
  rix_version <- utils::packageVersion("rix")

  generate_header <- function(rix_version,
                              nix_revision,
                              r_ver_text,
                              rix_call){

    if(identical(Sys.getenv("TESTTHAT"), "true")){
      sprintf('
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/%s.tar.gz") {};
',
nix_revision)
      } else {
        sprintf('# This file was generated by the {rix} R package v%s on %s
# with following call:
%s
# It uses nixpkgs\' revision %s for reproducibility purposes
# which will install R %s
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/%s.tar.gz") {};
',
rix_version,
Sys.Date(),
generate_rix_call(rix_call, nix_revision),
nix_revision,
r_ver_text,
nix_revision
)
    }

 }

# If `r_ver = "bleeding_edge"`, then this function gets used instead
generate_bleeding_edge_header <- function(rix_version,
                                          rix_call){
sprintf('# This file was generated by the {rix} R package v%s on %s
# with following call:
%s
# It uses a bleeding edge fork of nixpkgs! Only use this if you 
# really need bleeding edge packages. The environment generated
# by this file is NOT reproducible! If you need reproducible
# environments, replace "bleeding_edge" by "latest", or a
# specific R version.
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/r-daily.tar.gz") {};
',
rix_version,
Sys.Date(),
generate_rix_call(rix_call, "bleeding_edge")
)
}

  # Now we need to generate all the different sets of packages
  # to install. Let's start by the CRAN packages, current
  # and archived. The function below builds the strings.
  get_rPackages <- function(r_pkgs){

    # in case users pass something like c("dplyr", "tidyr@1.0.0")
    # r_pkgs will be "dplyr" only
    # and "tidyr@1.0.0" needs to be handled by fetchzips
    r_and_archive_pkgs <- detect_versions(r_pkgs)

    # overwrite r_pkgs
    r_pkgs <- r_and_archive_pkgs$cran_packages

    # get archive_pkgs
    archive_pkgs <- r_and_archive_pkgs$archive_packages

    r_pkgs <- if(ide == "code"){
                c(r_pkgs, "languageserver")
              } else {
                r_pkgs
              }

    rPackages <- paste(r_pkgs, collapse = ' ')

    rPackages <- gsub('\\.', '_', rPackages)

    list("rPackages" = rPackages,
         "archive_pkgs" = archive_pkgs)

  }

  # Get the two lists. One list is current CRAN packages
  # the other is archived CRAN packages.
  cran_pkgs <- get_rPackages(r_pkgs)

  # we need to know if the user wants R packages

  flag_rpkgs <- if(is.null(cran_pkgs$rPackages) | cran_pkgs$rPackages == ""){
                  ""
                } else {
                  "rpkgs"
                }

  # generate_* function generate the actual Nix code
  generate_rpkgs <- function(rPackages) {
    if (flag_rpkgs == ""){
      NULL
    } else {
      sprintf('rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) %s;
};
',
rPackages)
    }
  }

  # Texlive packages
  generate_tex_pkgs <- function(tex_pkgs) {
    if (!is.null(tex_pkgs)) {

      tex_pkgs <- paste(tex_pkgs, collapse = ' ')

    sprintf('tex = (pkgs.texlive.combine {
  inherit (pkgs.texlive) scheme-small %s;
});
',
tex_pkgs)
    }
  }

  flag_tex_pkgs <- if(is.null(tex_pkgs)){
                     ""
                   } else {
                     "tex"
                   }

  # system packages
  get_system_pkgs <- function(system_pkgs, r_pkgs){

    system_pkgs <- if(any(grepl("quarto", r_pkgs))){
                unique(c(system_pkgs, "quarto"))
              } else {
                system_pkgs
              }

    paste(system_pkgs, collapse = ' ')
  }

  flag_git_archive <- if(!is.null(cran_pkgs$archive) | !is.null(git_pkgs)){
                        "git_archive_pkgs"
                      } else {
                        ""
                      }

  generate_git_archived_packages <- function(git_pkgs, archive_pkgs){
    if(flag_git_archive == ""){
      NULL
    } else {
    sprintf('git_archive_pkgs = [%s];\n',
            fetchpkgs(git_pkgs, archive_pkgs)
            )
    }
  }


  # `R` needs to be added. If we were using the rWrapper
  # this wouldn't be needed, but we're not so we need
  # to add it.
  generate_system_pkgs <- function(system_pkgs, r_pkgs){
    sprintf('system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix %s;
};
',
get_system_pkgs(system_pkgs, r_pkgs))
  }

  generate_locale_variables <- function() {
    locale_defaults <- list(
      LANG = "en_US.UTF-8",
      LC_ALL = "en_US.UTF-8",
      LC_TIME = "en_US.UTF-8",
      LC_MONETARY = "en_US.UTF-8",
      LC_PAPER = "en_US.UTF-8",
      LC_MEASUREMENT = "en_US.UTF-8"
    )
    locale_variables <- getOption(
      "rix.nix_locale_variables",
      default = locale_defaults
    )
    valid_vars <- all(names(locale_variables) %in% names(locale_defaults))
    if (!isTRUE(valid_vars)) {
      stop("`options(rix.nix_locale_variables = list())` ",
        "only allows the following element names (locale variables):\n",
        paste(names(locale_defaults), collapse = "; "),
        call. = FALSE)
    }
    locale_vars <- paste(
      Map(function(x, nm) paste0(nm, ' = ', '"', x, '"'),
        nm = names(locale_variables), x = locale_variables),
      collapse = ";\n    "
    )
    paste0(locale_vars, ";\n")
  }

  generate_rstudio_pkgs <- function(ide, flag_git_archive, flag_rpkgs){
    if (flag_rpkgs == ""){
      return(NULL)
      } else if(ide == "rstudio"){
      sprintf('rstudio_pkgs = pkgs.rstudioWrapper.override {
  packages = [ %s %s ];
};
',
flag_git_archive,
flag_rpkgs
)
    } else {
      NULL
    }
  }

  flag_rstudio <- if (ide == "rstudio" & flag_rpkgs != "") "rstudio_pkgs" else ""

  shell_hook <- if (!is.null(shell_hook) && nzchar(shell_hook)) {
    paste0('shellHook = "', shell_hook, '";')
  } else {''}

  # Generate the shell
  generate_shell <- function(flag_git_archive,
                             flag_rpkgs){
    sprintf('in
  pkgs.mkShell {
    %s
    %s
    buildInputs = [ %s %s %s system_packages %s ];
      %s
  }',
  generate_locale_archive(detect_os()),
  generate_locale_variables(),
  flag_git_archive,
  flag_rpkgs,
  flag_tex_pkgs,
  flag_rstudio,
  shell_hook
  )

  }

  # Generate default.nix file
  default.nix <- paste(
    generate_header(rix_version,
                    nix_revision,
                    r_ver_text,
                    rix_call),
    generate_rpkgs(cran_pkgs$rPackages),
    generate_git_archived_packages(git_pkgs, cran_pkgs$archive_pkgs),
    generate_tex_pkgs(tex_pkgs),
    generate_system_pkgs(system_pkgs, r_pkgs),
    generate_rstudio_pkgs(ide, flag_git_archive, flag_rpkgs),
    generate_shell(flag_git_archive, flag_rpkgs),
    collapse = "\n"
    )

  default.nix <- readLines(textConnection(default.nix))

  if(print){
    cat(default.nix, sep = "\n")
  }

  if(!file.exists(project_path) || overwrite){
    writeLines(default.nix, project_path)
  } else {
    stop(paste0("File exists at ", project_path, ". Set `overwrite == TRUE` to overwrite."))
  }



}
```
```{r, tests-rix_rstudio}
testthat::test_that("rix(), ide is 'rstudio', Linux", {

  skip_if(Sys.info()["sysname"] == "Darwin")

  path_default_nix <- tempdir()

  save_default_nix_test <- function(ide, path_default_nix) {

    rix(r_ver = "4.3.1",
        r_pkgs = c("dplyr", "janitor", "AER@1.2-8", "quarto"),
        tex_pkgs = c("amsmath"),
        git_pkgs = list(
          list(package_name = "housing",
               repo_url = "https://github.com/rap4all/housing/",
               branch_name = "fusen",
               commit = "1c860959310b80e67c41f7bbdc3e84cef00df18e"),
          list(package_name = "fusen",
               repo_url = "https://github.com/ThinkR-open/fusen",
               branch_name = "main",
               commit = "d617172447d2947efb20ad6a4463742b8a5d79dc")
        ),
        ide = ide,
        project_path = path_default_nix,
        overwrite = TRUE,
        shell_hook = NULL)

    paste0(path_default_nix, "/default.nix")

  }

  testthat::announce_snapshot_file("rix/rstudio_default.nix")

  testthat::expect_snapshot_file(
    path = save_default_nix_test(ide = "rstudio", path_default_nix),
    name = "rstudio_default.nix",
  )


})

```

```{r, tests-rix}
testthat::test_that("rix(), ide is 'other' or 'code'", {

  path_default_nix <- tempdir()

  save_default_nix_test <- function(ide, path_default_nix) {

    rix(r_ver = "4.3.1",
        r_pkgs = c("dplyr", "janitor", "AER@1.2-8", "quarto"),
        tex_pkgs = c("amsmath"),
        git_pkgs = list(
          list(package_name = "housing",
               repo_url = "https://github.com/rap4all/housing/",
               branch_name = "fusen",
               commit = "1c860959310b80e67c41f7bbdc3e84cef00df18e"),
          list(package_name = "fusen",
               repo_url = "https://github.com/ThinkR-open/fusen",
               branch_name = "main",
               commit = "d617172447d2947efb20ad6a4463742b8a5d79dc")
        ),
        ide = ide,
        project_path = path_default_nix,
        overwrite = TRUE,
        shell_hook = NULL)

    paste0(path_default_nix, "/default.nix")

  }


  testthat::announce_snapshot_file("rix/other_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(ide = "other",
                                           path_default_nix),
              name = "other_default.nix"
            )

  testthat::announce_snapshot_file("rix/code_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(ide = "code",
                                           path_default_nix),
              name = "code_default.nix"
              )

})

```

```{r, tests-add_quarto_to_sys_pkgs}
testthat::test_that("Quarto gets added to sys packages", {

  path_default_nix <- tempdir()

  save_default_nix_test <- function(pkgs, interface, path_default_nix) {

      rix(r_ver = "4.3.1",
          r_pkgs = pkgs,
          ide = interface,
          project_path = path_default_nix,
          overwrite = TRUE,
          shell_hook = NULL
          )

      paste0(path_default_nix, "/default.nix")

  }

  testthat::announce_snapshot_file("rix/no_quarto_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(pkgs = "dplyr",                                       interface = "other",
                                           path_default_nix),
              name = "no_quarto_default.nix",
              )

  testthat::announce_snapshot_file("rix/yes_quarto_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(pkgs = c("dplyr", "quarto"),
                                           interface = "other",
                                           path_default_nix),
              name = "yes_quarto_default.nix"
            )
})

```

```{r, tests-null_pkgs_rstudio_ide}
testthat::test_that("r_pkgs = NULL and ide = 'rstudio' work together", {

  skip_if(Sys.info()["sysname"] == "Darwin")

  path_default_nix <- tempdir()

  save_default_nix_test <- function(pkgs, interface, path_default_nix) {

    rix(r_ver = "4.3.1",
        r_pkgs = pkgs,
        ide = interface,
        project_path = path_default_nix,
        overwrite = TRUE,
        shell_hook = NULL
        )

    paste0(path_default_nix, "/default.nix")

  }

  testthat::announce_snapshot_file("rix/null_pkgs_rstudio.nix")

  testthat::expect_snapshot_file(
   path = save_default_nix_test(pkgs = NULL,
     interface = "rstudio",
     path_default_nix),
   name = "null_pkgs_rstudio.nix"
  )

})

```

```{r, tests-warning_macos_rstudio}
testthat::test_that("If on darwin and ide = rstudio, raise warning", {

  skip_if(Sys.info()["sysname"] != "Darwin")

  path_default_nix <- tempdir()

  save_default_nix_test <- function(path_default_nix) {

    rix(r_ver = "4.3.1",
        ide = "rstudio",
        r_pkgs = NULL,
        project_path = path_default_nix,
        overwrite = TRUE,
        shell_hook = NULL
      )

    paste0(path_default_nix, "/default.nix")

  }

  testthat::expect_warning(
    save_default_nix_test(path_default_nix),
    regexp = "refer to the macOS"
  )

})

```

