---
title: "Functions for Github Actions CI/CD service"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

The function below copies a Github actions workflow file into the
`.github/workflows/run-pipeline.yaml`:

```{r function-tar_nix_ga}
#' tar_nix_ga Run a {targets} pipeline on Github Actions.
#' @details This function puts a `.yaml` file inside the `.github/workflows/`
#' folders on the root of your project. This workflow file will use the
#' projects `default.nix` file to generate the development environment on
#' Github Actions and will then run the projects {targets} pipeline. Make
#' sure to give read and write permissions to the Github Actions bot.
#' @return Nothing, copies file to a diretory.
#' @export
#' @examples
#' \dontrun{
#'   tar_nix_ga()
#' }
tar_nix_ga <- function(){

  # is this being tested? If no, set the path to ".github/workflows"
  # if yes, set it to a temporary directory
  if(!identical(Sys.getenv("TESTTHAT"), "true")){

    # Add an empty .gitignore file if there isn’t any

    if(file.exists(".gitignore")){
      NULL
    } else {
      file.create(".gitignore")
    }

    path <- ".github/workflows"

    dir.create(path, recursive = TRUE)
  } else {
    path <- tempdir()
  }

  source <- system.file(
        file.path("extdata", "run-pipeline.yaml"),
        package = "rix",
    mustWork = TRUE
  )

  file.copy(source, path, overwrite = TRUE)
  message("GitHub Actions workflow file save to: ", path)
  if(identical(Sys.getenv("TESTTHAT"), "true")) paste0(path, "/run-pipeline.yaml")
  }
```

Be sure to give Github Actions workflows read and write permissions.

```{r tests-tar_nix_ga}
testthat::test_that("Snapshot test of all features of rix", {

  testthat::announce_snapshot_file("cicd/run-pipeline.yaml")

  testthat::expect_snapshot_file(
              path = tar_nix_ga(),
              name = "run-pipeline.yaml"
              )
})
```

