---
title: "Find revision"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

This function takes an R version as an input and returns the Nix revision that
provides it:


```{r function-find_rev}
#' find_rev Find the right Nix revision
#' @param r_version Character. R version to look for, for example, "4.2.0". If a nixpkgs revision is provided instead, this gets returned.
#' @return A character. The Nix revision to use
#'
#' @examples
#' find_rev("4.2.0")
find_rev <- function(r_version) {

  stopifnot("r_version has to be a character." = is.character(r_version))

  if(r_version == "latest"){
    return(get_latest(r_version))
  } else if(nchar(r_version) == 40){
    return(r_version)
  } else {

    temp <- new.env(parent = emptyenv())

    data(list = "r_nix_revs",
         package = "rix",
         envir = temp)

    get("r_nix_revs", envir = temp)

    output <- r_nix_revs$revision[r_nix_revs$version == r_version]

    stopifnot("Error: the provided R version is likely wrong. Please check that you provided a correct R version. You can list available versions using `available_r()`" = !identical(character(0), output))

    output
  }

}

```

```{r tests-find_rev}
testthat::test_that("find_rev returns correct nixpkgs hash", {
  testthat::expect_equal(
              find_rev("4.2.2"),
              "8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8"
            )

  testthat::expect_equal(
              find_rev("8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8"),
              "8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8"
            )
})
```
