---
title: "nix_build"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

The function below is to invoke the shell command `nix-build` from a R 
session.

```{r function-nix_build}
#' Invoke shell command `nix-build` from an R session
#' @param project_path Path to the folder where the `default.nix` file resides. 
#' The default is `"."`, which is the working directory in the current R
#' session.
#' @param exec_mode Either `"blocking"` (default) or `"non-blocking`. This
#' will either block the R session while the `nix-build` shell command is
#' executed, or run `nix-build` in the background ("non-blocking").
#' @return integer of the process ID (PID) of `nix-build` shell command
#' launched, if `nix_build()` call is assigned to an R object. Otherwise, it 
#' will be returned invisibly.
#' @details The `nix-build` command line interface has more arguments. We will
#' probably not support all of them in this R wrapper, but currently we have
#' support for the following `nix-build` flags:
#' - `--max-jobs`: Maximum number of build jobs done in parallel by Nix.
#'   According to the official docs of Nix, it defaults to `1`, which is one
#'   core. This option can be useful for shared memory multiprocessing or
#'   systems with high I/O latency. To set `--max-jobs` used, you can declare
#'   with `options(rix.nix_build_max_jobs = <integer>)`. Once you call
#'   `nix_build()` the flag will be propagated to the call of `nix-build`.
#' @export
#' @examples
#' \dontrun{
#'   nix_build()
#' }
nix_build <- function(project_path = ".",
                      exec_mode = c("blocking", "non-blocking")) {
  # if nix store is not PATH variable; e.g. on macOS (system's) RStudio
  PATH <- set_nix_path()
  if (isTRUE(nzchar(Sys.getenv("NIX_STORE")))) {
    # for Nix R sessions, guarantee that the system's user library 
    # (R_LIBS_USER) is not in the search path for packages => run-time purity
    current_libpaths <- .libPaths()
    # don't do this in covr test environment, because this sets R_LIBS_USER
    # to multiple paths
    if (isFALSE(nzchar(Sys.getenv("R_COVR")))) {
      remove_r_libs_user()
    }
  } else {
    LD_LIBRARY_PATH_default <- Sys.getenv("LD_LIBRARY_PATH")
    if (nzchar(LD_LIBRARY_PATH_default)) {
      # On some systems, like Ubuntu 22.04, we found that a preset 
      # `LD_LIBRARY_PATH` environment variable in the system's R session
      # (R installed via apt) is responsible for causing  a segmentation fault
      # for both `nix-build` and `nix-shell` when invoked via 
      # `sys::exec_internal`, `base::system()` or `base::system2()` from R.
      # This seems due to incompatible linked libraries or permission issue that
      # conflict when mixing Nix packages and libraries from the system.
      # Therefore, we set it to `""` and set  back the default (old)
      # `LD_LIBRARY_PATH` when `with_nix()` exits. For newer RStudio versions,
      # LD_LIBRARY_PATH is not `""` anymore
      # https://github.com/rstudio/rstudio/issues/12585
      fix_ld_library_path()
      cat("* Current LD_LIBRARY_PATH in system R session is:",
        LD_LIBRARY_PATH_default)
      cat("\n", "Setting `LD_LIBRARY_PATH` to `''` during `nix_build()`")
    }
  }
  has_nix_build <- nix_build_installed() # TRUE if yes, FALSE if no
  nix_file <- normalizePath(file.path(project_path, "default.nix"))

  stopifnot(
    "`project_path` must be character of length 1." =
      is.character(project_path) && length(project_path) == 1L,
    "`project_path` has no `default.nix` file. Use one that contains `default.nix`" =
      file.exists(nix_file),
    "`nix-build` not available. To install, we suggest you follow https://zero-to-nix.com/start/install ." =
      isTRUE(has_nix_build)
  )
  exec_mode <- match.arg(exec_mode)
 
  max_jobs <- getOption("rix.nix_build_max_jobs", default = 1L)
  stopifnot("option `rix.nix_build_max_jobs` is not integerish" =
    is_integerish(max_jobs))
  max_jobs <- as.integer(max_jobs)
  
  cmd <- "nix-build"

  if (max_jobs == 1L) {
    args <- nix_file
  } else {
    args <- c("--max-jobs", as.character(max_jobs), nix_file)
  }

  cat(paste0("Launching `", paste0(cmd, args, collapse = " "), "`", " in ",
    exec_mode, " mode\n"))

  proc <- switch(exec_mode,
    "blocking" = sys::exec_internal(cmd = cmd, args = args),
    "non-blocking" = sys::exec_background(cmd = cmd, args = args),
    stop('invalid `exec_mode`. Either use "blocking" or "non-blocking"')
  )

  if (exec_mode == "non-blocking") {
    poll_sys_proc_nonblocking(cmd, proc, what = "nix-build")
  } else if (exec_mode == "blocking") {
    poll_sys_proc_blocking(cmd, proc, what = "nix-build")
  }

  # todo (?): clean zombies for background/non-blocking mode
  
  # set back library paths to state before calling `with_nix()`
  
  if (isTRUE(nzchar(Sys.getenv("NIX_STORE")))) {
    # set back library paths to state before calling `with_nix()`
    .libPaths(new = current_libpaths)
  } else {
    if (nzchar(LD_LIBRARY_PATH_default)) {
       # set old LD_LIBRARY_PATH (only if system's R session and if it wasn't
       # `""`)
      on.exit(Sys.setenv(LD_LIBRARY_PATH=LD_LIBRARY_PATH_default))
    }
  }
  
  return(invisible(proc))
}

#' @noRd
remove_r_libs_user <- function() {
  current_paths <- .libPaths()
  userlib_paths <- Sys.getenv("R_LIBS_USER")
  user_dir <- grep(paste(userlib_paths, collapse = "|"), current_paths)
  new_paths <- current_paths[-user_dir]
  # sets new library path without user library, making nix-R pure at 
  # run-time
  invisible(.libPaths(new_paths))
}

#' @noRd
fix_ld_library_path <- function() {
  old_ld_library_path <- Sys.getenv("LD_LIBRARY_PATH")
  Sys.setenv(LD_LIBRARY_PATH="")
  invisible(old_ld_library_path)
}

#' @noRd
poll_sys_proc_blocking <- function(cmd, proc,
                                   what = c("nix-build", "expr")) {
  what <- match.arg(what)
  status <- proc$status
  if (status == 0L) {
    cat(paste0("\n==> ", sys::as_text(proc$stdout)))
    cat(paste0("\n==> `", what, "` succeeded!", "\n"))
  } else {
    msg <- nix_build_exit_msg()
    cat(paste0("`", cmd, "`", " failed with ", msg))
  }
  return(invisible(status))
}

#' @noRd
poll_sys_proc_nonblocking <- function(cmd, proc, 
                                      what = c("nix-build", "expr")) {
  what <- match.arg(what)
  cat(paste0("\n==> Process ID (PID) is ", proc, "."))
  cat("\n==> Receiving stdout and stderr streams...\n")
  status <- sys::exec_status(proc, wait = TRUE)
  if (status == 0L) {
    cat(paste0("\n==> `", what, "` succeeded!"))
  }
  return(invisible(status))
}

#' @noRd
is_integerish <- function(x, tol = .Machine$double.eps^0.5) {
  return(abs(x - round(x)) < tol)
}

#' @noRd
nix_build_installed <- function() {
  exit_code <- system2("command", "-v", "nix-build")
  if (exit_code == 0L) {
    return(invisible(TRUE))
  } else {
    return(invisible(FALSE))
  }
}

#' @noRd
nix_build_exit_msg <- function(x) {
  x_char <- as.character(x)
  
  err_msg <- switch(
    x_char,
    "100" = "generic build failure (100).",
    "101" = "build timeout (101).",
    "102" = "hash mismatch (102).",
    "104" = "not deterministic (104).",
    stop(paste0("general exit code ", x_char, "."))
  )
  
  return(err_msg)
}
```

```{r, tests-nix_build}

testthat::test_that("Testing that `nix_build()` builds derivation", {
  
  if (isFALSE(is_nix_rsession())) {
    # needed for the GitHub test runners with system's R
    set_nix_path()
  }
  
  skip_if_not(nix_shell_available())
  
  # skip_on_covr()

  path_subshell <- tempdir()

  rix_init(
    project_path = path_subshell,
    rprofile_action = "overwrite",
    message_type = "simple"
  )

  rix(
    r_ver = "latest",
    overwrite = TRUE,
    project_path = path_subshell
  )

  out <- nix_build(
    project_path = path_subshell,
    exec_mode = "blocking"
  )

  # exit status 0L is success
  testthat::expect_true(
    out$status == 0L
  )
})
```