---
title: "List available R versions"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

This function returns available R versions:

```{r function-available_r}
#' List available R versions from Nixpkgs
#' @return A character vector containing the available R versions.
#' @export
#'
#' @examples
#' available_r()
available_r <- function(){

  temp <- new.env(parent = emptyenv())

  data(list = "r_nix_revs",
       package = "rix",
       envir = temp)

  get("r_nix_revs", envir = temp)

  c("latest", r_nix_revs$version)
}

```

```{r tests-available_r}
testthat::test_that("available_r lists all available r versions", {
  testthat::expect_equal(
              available_r(),
              c("latest", "3.0.2",  "3.0.3",  "3.1.0",  "3.1.2",  "3.1.3",  "3.2.0",  "3.2.1",
                "3.2.2",  "3.2.3",  "3.2.4",  "3.3.3",  "3.4.0",  "3.4.1",  "3.4.2",  "3.4.3",
                "3.4.4",  "3.5.0",  "3.5.1",  "3.5.2",  "3.5.3",  "3.6.0",  "3.6.1",  "3.6.2",
                "3.6.3",  "4.0.0",  "4.0.2",  "4.0.3",  "4.0.4",  "4.1.1",  "4.1.2",  "4.1.3",
                "4.2.0",  "4.2.1",  "4.2.2",  "4.2.3",  "4.3.1", "4.3.2"
                )
            )
})


```
