---
title: "Get latest R version"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

The function below will return the very latest commit from the unstable branch
of `NixOS/nixpkgs`. This will make sure that users that want to use the most
up-to-date version of R and R packages can do so:

```{r function-get_latest}
#' get_latest Get the latest R version and packages
#' @return A character. The commit hash of the latest nixpkgs-unstable revision
#' @importFrom httr content GET stop_for_status
#' @importFrom jsonlite fromJSON
#'
#' @examples
get_latest <- function() {
  api_url <- "https://api.github.com/repos/NixOS/nixpkgs/commits?sha=nixpkgs-unstable"

  tryCatch({
    response <- httr::GET(url = api_url)
    httr::stop_for_status(response)
    commit_data <- jsonlite::fromJSON(httr::content(response, "text"))
    latest_commit <- commit_data$sha[1]
    return(latest_commit)
  }, error = function(e) {
    cat("Error:", e$message, "\n")
    return(NULL)
  })
}
```

```{r, tests-get_latest}
testthat::test_that("get_latest() fails as expected if error", {
  is_internet_down <- function() {
    !curl::has_internet()
  }

  testthat::local_mocked_bindings(is_internet_down = function(...) TRUE)
  testthat::expect_error(get_latest())

})

```
