---
title: "OS detection"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

This function detects the operating system:

```{r function-detect_os}
#' detect_os Detects the current OS
#' @return A character. One of Linux or Darwin (Windows is also Linux)
#'
#' @examples
#' detect_os()
detect_os <- function(){
  os <- Sys.info()["sysname"]
  if(os == "Windows"){
    "Linux"
  } else {
    os
  }
}
```

This function adds deals with locale on Linux (and WSL2):

```{r function-generate_locale_archive}
#' generate_locale_archive Adds a line to the shellHook to avoid locale warnings
#' @return A character.
#'
#' @examples
#' generate_locale_archive("Linux")
generate_locale_archive <- function(os){
  if(detect_os() == "Linux"){
    'LOCALE_ARCHIVE = \"${pkgs.glibcLocales}/lib/locale/locale-archive\";'
  } else if(detect_os() == "Darwin") {
    ''
  } else {
    stop("Operating System unsupported")
  }
}
```
