---
title: "Interactive use"
output: html_document
editor_options:
  chunk_output_type: console
---

## Introduction

This vignette describes interactive use of environments built with `{rix}` using
a GUI editor like RStudio. I will discuss two scenarios: one in which you
already have R and RStudio installed on your operating system using the usual
installation method for your operating system, and another in which you used Nix
to install R and RStudio (or any other IDE).

## Scenario 1: you installed R and RStudio as usual

Let's suppose that you are already running R and RStudio and that you wish to
start using `{rix}` to define reproducible environments for your new projects
starting today. These environments will get built using the Nix package manager
and will not only include the required R packages for your project but also a
specific version of R, and any required system-level dependency as well. If you
are used to using RStudio, then you also need to install RStudio using Nix in
these project-specific environments. To run a project-specific version of
RStudio and R, you will first need to create a `default.nix` file and build the
environment defined therein using Nix. Once this is done, you then need to
activate the environment before running this project-specific version of
RStudio. Suppose for example that you generated a `default.nix` file for a
project called "kmeans", and suppose that this project is in the following path:
`~/Documents/kmeans` (on Windows it would be something like
`C:\Users\Billy\Documents\kmeans`). Navigate to that folder using your terminal,
and then run `nix-shell`. You will then be *dropped into* a Nix shell. From
there you can type `rstudio` to run this project specific version of RStudio
with all the packages. You can then work on it as usual.

You can also define a shortcut to a project that will take care of activating
the environment and launching rstudio. For example, you could define a bash
alias like this:

```
alias kmeans='nix-shell ~/Documents/kmeans/default.nix --run rstudio
```

which would then execute RStudio in the right project by simply typing `kmeans`
in a terminal. It's also possible to create an executable script that you can
save in your PATH:

```
#!/usr/bin/env nix-shell
#!nix-shell /home/Billy/Document/kmeans/default.nix -i bash
rstudio
```

Name this script something like `kmeans_project`, make it executable (using
`chmod +x kmeans_project`), and now you can run RStudio within this environment
from anywhere.

## Scenario 2: you install R and RStudio using Nix

If you don't have R installed you cannot use the `{rix}` package to generate new
expressions. In this case you might consider installing Nix first, and then
running the following command inside your terminal to get dropped into a
temporary Nix shell, which you can then use to generate new `default.nix` files:

```
nix-shell --expr "$(curl -sl https://raw.githubusercontent.com/b-rodrigues/rix/master/inst/extdata/default.nix)"
```

Running the command above will download R and `{rix}` and then start an R
session inside your terminal. You can now run something like this:

```
rix(r_ver = "current",
    r_pkgs = c("dplyr", "ggplot2"),
    other_pkgs = NULL,
    git_pkgs = NULL,
    ide = "rstudio",
    path = ".", # change to a project's path
    overwrite = TRUE)
```

to generate a `default.nix`, and then use that file to generate an environment
with R, Rstudio, `{dplyr}` and `{ggplot2}`. If you need to add packages for your
project, rerun the command above, but add the needed packages to `r_pkgs`.

## Other IDEs

Visual Studio Code and Emacs have been tested and unlike RStudio, you can use
the version of either VS Code or Emacs that you already have installed on your
system. But there's nothing stopping you from installing a project-specific
version of VS Code or Emacs as well. Configuration and settings should be
accessible across every version from every environment, since these are globally
defined at the level of your system.
