# This file was generated by the {rix} R package v0.6.0 on 2024-02-12
# with following call:
# >rix(r_ver = "f597e7e9fcf37d8ed14a12835ede0a7d362314bd",
#  > project_path = path_env_1_2,
#  > overwrite = TRUE,
#  > shell_hook = "R")
# It uses nixpkgs' revision f597e7e9fcf37d8ed14a12835ede0a7d362314bd for reproducibility purposes
# which will install R version 4.2.0
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/f597e7e9fcf37d8ed14a12835ede0a7d362314bd.tar.gz") {};
    system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix ;
};
  in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [    system_packages  ];
      shellHook = "R";
  }
