# WARNING - Generated by {fusen} from dev/flat_nix_build.Rmd: do not edit by hand


testthat::test_that("Testing that `nix_build()` builds derivation", {
  
  skip_if_not(nix_shell_available())
  
  # skip_on_covr()

  path_subshell <- tempdir()

  rix_init(
    project_path = path_subshell,
    rprofile_action = "overwrite",
    message_type = "simple"
  )

  rix(
    r_ver = "latest",
    overwrite = TRUE,
    project_path = path_subshell
  )

  out <- nix_build(
    project_path = path_subshell,
    exec_mode = "blocking"
  )

  # exit status 0L is success
  testthat::expect_true(
    out$status == 0L
  )
})
