# WARNING - Generated by {fusen} from dev/flat_build_envs.Rmd: do not edit by hand

testthat::test_that("find_rev returns correct nixpkgs hash", {
  testthat::expect_equal(
              find_rev("4.2.2"),
              "8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8"
            )

  testthat::expect_equal(
              find_rev("8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8"),
              "8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8"
            )
})

testthat::test_that("available_r lists all available r versions", {
  testthat::expect_equal(
              available_r(),
              c("latest", "3.0.2",  "3.0.3",  "3.1.0",  "3.1.2",  "3.1.3",  "3.2.0",  "3.2.1",
                "3.2.2",  "3.2.3",  "3.2.4",  "3.3.3",  "3.4.0",  "3.4.1",  "3.4.2",  "3.4.3",
                "3.4.4",  "3.5.0",  "3.5.1",  "3.5.2",  "3.5.3",  "3.6.0",  "3.6.1",  "3.6.2",
                "3.6.3",  "4.0.0",  "4.0.2",  "4.0.3",  "4.0.4",  "4.1.1",  "4.1.2",  "4.1.3",
                "4.2.0",  "4.2.1",  "4.2.2",  "4.2.3",  "4.3.1"
                )
            )
})



testthat::test_that("get_sri_hash_deps returns correct sri hash and dependencies of R packages", {
  testthat::expect_equal(
              get_sri_hash_deps("https://github.com/rap4all/housing/",
                                "fusen",
                                "1c860959310b80e67c41f7bbdc3e84cef00df18e"),
              list(
                "sri_hash" = "sha256-s4KGtfKQ7hL0sfDhGb4BpBpspfefBN6hf+XlslqyEn4=",
                "deps" = "dplyr ggplot2 janitor purrr readxl rlang rvest stringr tidyr"
              )
            )
})


testthat::test_that("Snapshot test of all features of rix", {
  save_default_nix_test <- function() {

    path_default_nix <- tempdir()

    rix(r_ver = "4.3.1",
        r_pkgs = c("dplyr", "janitor", "AER@1.2-8", "quarto"),
        system_pkgs = c("quarto"),
        tex_pkgs = c("amsmath"),
        git_pkgs = list(
          list(package_name = "housing",
               repo_url = "https://github.com/rap4all/housing/",
               branch_name = "fusen",
               commit = "1c860959310b80e67c41f7bbdc3e84cef00df18e"),
          list(package_name = "fusen",
               repo_url = "https://github.com/ThinkR-open/fusen",
               branch_name = "main",
               commit = "d617172447d2947efb20ad6a4463742b8a5d79dc")
        ),
        ide = "rstudio",
        project_path = path_default_nix,
        overwrite = TRUE)

    paste0(path_default_nix, "/default.nix")

  }

  testthat::announce_snapshot_file("find_rev/default.nix")

  testthat::expect_snapshot_file(path = save_default_nix_test(),
                                 name = "default.nix",
                                 #compare = compare_file_text(
                                 #  new = "find_rev/default.nix",
                                 #  old = "target_default.nix")
                                 )

})
