# WARNING - Generated by {fusen} from dev/flat_get_latest.Rmd: do not edit by hand

testthat::test_that("get_latest() fails gracefully if no internet", {

  with_mocked_bindings(
    expect_error(get_latest(),
                 "You don't seem to be connected"),
     `curl::has_internet` = function(...) FALSE
  )

})

