# WARNING - Generated by {fusen} from dev/flat_with_nix.Rmd: do not edit by hand

testthat::test_that("Testing `with_nix()` if Nix is installed", {

  skip_if_not(nix_shell_available())
  # R version 3.5.3 on Nixpkgs does not build for aarch64-darwin (ARM macOS)
  skip_if(Sys.info()["sysname"] == "Darwin")

  #skip_on_covr()

  path_subshell <- withr::local_tempdir()

  rix_init(
    project_path = path_subshell,
    rprofile_action = "overwrite",
    message_type = "simple"
  )

  rix(
    r_ver = "3.5.3",
    overwrite = TRUE,
    project_path = path_subshell
  )

  out_subshell <- with_nix(
    expr = function(){
      set.seed(1234)
      a <- sample(seq(1, 10), 5)
      set.seed(NULL)
      return(a)
    },
    program = "R",
    exec_mode = "non-blocking",
    project_path = path_subshell,
    message_type = "simple"
  )

  # On a recent version of R, set.seed(1234);sample(seq(1,10), 5)
  # returns c(10, 6, 5, 4, 1)
  # but not on versions prior to 3.6
  testthat::expect_true(
    all(c(2, 6, 5, 8, 9) == out_subshell)
  )
})

testthat::test_that("Test `with_nix()` if Nix is installed on R 4.2.0", {
  
  skip_if_not(nix_shell_available())
  
  path_subshell <- withr::local_tempdir()
  
  rix_init(
    project_path = path_subshell,
    rprofile_action = "overwrite",
    message_type = "simple"
  )
  
  rix(
    r_ver = "4.2.0",
    overwrite = TRUE,
    project_path = path_subshell
  )
  
  df <- data.frame(a = 1:3, b = 4:6)
  
  out_subshell <- with_nix(
    expr = function() {
      as.vector(x = data.frame(a = 1:3, b = 4:6), mode = "list")
    },
    program = "R",
    exec_mode = "blocking",
    project_path = path_subshell,
    message_type = "verbose"
  )
  
  testthat::expect_false(
    inherits(out_subshell, "data.frame")
  )
})

