# WARNING - Generated by {fusen} from dev/flat_rix.Rmd: do not edit by hand

testthat::test_that("Snapshot test of rix()", {

  path_default_nix <- tempdir()

  save_default_nix_test <- function(ide, path_default_nix) {

    rix(r_ver = "4.3.1",
        r_pkgs = c("dplyr", "janitor", "AER@1.2-8", "quarto"),
        tex_pkgs = c("amsmath"),
        git_pkgs = list(
          list(package_name = "housing",
               repo_url = "https://github.com/rap4all/housing/",
               branch_name = "fusen",
               commit = "1c860959310b80e67c41f7bbdc3e84cef00df18e"),
          list(package_name = "fusen",
               repo_url = "https://github.com/ThinkR-open/fusen",
               branch_name = "main",
               commit = "d617172447d2947efb20ad6a4463742b8a5d79dc")
        ),
        ide = ide,
        project_path = path_default_nix,
        overwrite = TRUE)

    paste0(path_default_nix, "/default.nix")

  }

  testthat::announce_snapshot_file("find_rev/rstudio_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(ide = "rstudio",
                                           path_default_nix),
              name = "rstudio_default.nix",
              )

  testthat::announce_snapshot_file("find_rev/other_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(ide = "other",
                                           path_default_nix),
              name = "other_default.nix"
            )

  testthat::announce_snapshot_file("find_rev/code_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(ide = "code",
                                           path_default_nix),
              name = "code_default.nix"
              )

})


testthat::test_that("Quarto gets added to sys packages", {

  path_default_nix <- tempdir()

  save_default_nix_test <- function(pkgs, path_default_nix) {

    rix(r_ver = "4.3.1",
        r_pkgs = pkgs,
        ide = "other",
        project_path = path_default_nix,
        overwrite = TRUE)

    paste0(path_default_nix, "/default.nix")

  }

  testthat::announce_snapshot_file("find_rev/no_quarto_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(pkgs = "dplyr", path_default_nix),
              name = "no_quarto_default.nix",
              )

  testthat::announce_snapshot_file("find_rev/yes_quarto_default.nix")

  testthat::expect_snapshot_file(
              path = save_default_nix_test(pkgs = c("dplyr", "quarto"),
                                           path_default_nix),
              name = "yes_quarto_default.nix"
            )

})

