# WARNING - Generated by {fusen} from dev/flat_with_nix.Rmd: do not edit by hand

testthat::test_that("Test 2 for with_nix() if Nix is installed", {
  
  skip_if_not(nix_shell_available())
  
  path_subshell <- tempdir()
  
  rix_init(
    project_path = path_subshell,
    rprofile_action = "overwrite",
    message_type = "simple"
  )
  
  rix(
    r_ver = "4.2.0",
    overwrite = TRUE,
    project_path = path_subshell
  )
  
  df <- data.frame(a = 1:3, b = 4:6)
  
  df_as_vector <- function(x) {
    out <- as.vector(x = x, mode = "list")
    return(out)
  }
  
  out_subshell <- with_nix(
    expr = function() df_as_vector(x = df),
    program = "R",
    exec_mode = "non-blocking",
    project_path = path_subshell,
    message_type = "verbose"
  )
  
  testthat::expect_false(
    inherits(out_subshell, "data.frame")
  )
})


testthat::test_that("Testing with_nix() if Nix is installed", {

  skip_if_not(nix_shell_available())

  path_subshell <- tempdir()

  rix_init(
    project_path = path_subshell,
    rprofile_action = "overwrite",
    message_type = "simple"
  )

  rix(
    r_ver = "3.5.3",
    overwrite = TRUE,
    project_path = path_subshell
  )

  out_subshell <- with_nix(
    expr = function(){
      set.seed(1234)
      a <- sample(seq(1, 10), 5)
      set.seed(NULL)
      return(a)
    },
    program = "R",
    exec_mode = "non-blocking",
    project_path = path_subshell,
    message_type = "simple"
  )

  # On a recent version of R, set.seed(1234);sample(seq(1,10), 5)
  # returns c(10, 6, 5, 4, 1)
  # but not on versions prior to 3.6
  testthat::expect_true(
    all(c(2, 6, 5, 8, 9) == out_subshell)
  )


})

