{
  description = "R development environment generated by rix (minimal template)";

  inputs = {
    nixpkgs.url = "{{NIXPKGS_URL}}";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Import the package definitions generated by rix
        rixEnv = import ./.rixpackages.nix pkgs;

        # R with all packages
        r-with-packages = pkgs.rWrapper.override {
          packages = [ rixEnv.rpkgs ];
        };

      in {
        # Default package
        packages.default = r-with-packages;

        # Development shell
        devShells.default = rixEnv.shell;

        # App to run R directly
        apps.default = {
          type = "app";
          program = "${r-with-packages}/bin/R";
        };
      });
}
