{
  description = "R development environment with VS Code (generated by rix)";

  inputs = {
    nixpkgs.url = "{{NIXPKGS_URL}}";
    flake-utils.url = "github:numtide/flake-utils";
  };

  nixConfig = {
    allowUnfree = true;
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Import the package definitions generated by rix
        rixEnv = import ./.rixpackages.nix pkgs;

        # R with all packages (includes languageserver from rix())
        r-with-packages = pkgs.rWrapper.override {
          packages = [ rixEnv.rpkgs ];
        };

      in {
        # Packages
        packages = {
          default = r-with-packages;
          r = r-with-packages;
        };

        # Development shell with VS Code
        devShells = {
          default = pkgs.mkShell {
            buildInputs = [
              r-with-packages
              pkgs.vscode
            ] ++ rixEnv.system_packages;
            inherit (rixEnv.shell) LOCALE_ARCHIVE LANG LC_ALL LC_TIME;
            inherit (rixEnv.shell) LC_MONETARY LC_PAPER LC_MEASUREMENT;
          };

          # R-only shell
          r = rixEnv.shell;

          # VS Code only (no R in path)
          code = pkgs.mkShell {
            buildInputs = [ pkgs.vscode ];
          };
        };

        # Apps
        apps = {
          default = {
            type = "app";
            program = "${pkgs.vscode}/bin/code";
          };
          code = {
            type = "app";
            program = "${pkgs.vscode}/bin/code";
          };
          r = {
            type = "app";
            program = "${r-with-packages}/bin/R";
          };
        };
      });
}
