# WARNING - Generated by {fusen} from dev/cran_archive.Rmd: do not edit by hand

#' @noRd
detect_versions <- function(r_pkgs){
  if(any(grepl("@", r_pkgs))){

    cran_packages <- Filter(\(x)(!grepl("@", x)), r_pkgs)
    archive_packages <- Filter(\(x)(grepl("@", x)), r_pkgs)

    output <- list(
      "cran_packages" = cran_packages,
      "archive_packages" = archive_packages
    )

  } else {
    output <- list(
      "cran_packages" = r_pkgs,
      "archive_packages" = NULL
    )
  }

}
