# WARNING - Generated by {fusen} from dev/build_envs.Rmd: do not edit by hand

#' find_rev Find the right Nix revision
#' @param r_version Character. R version to look for, for example, "4.2.0"
#' @return A character. The Nix revision to use
#' @export
#'
#' @examples
#' find_rev("4.2.0")
find_rev <- function(r_version){

  temp <- new.env(parent = emptyenv())

  data(list = "r_nix_revs",
       package = "rix",
       envir = temp)

  get("r_nix_revs", envir = temp)

  output <- r_nix_revs$revision[r_nix_revs$version == r_version]

  stopifnot("Error: the provided R version is likely wrong. Please check that you provided a correct R version. You can list available versions using `available_r()`" = !identical(character(0), output))

  output
}


#' available_r List available R versions
#' @return A character vector containing the available R versrions.
#' @export
#'
#' @examples
#' available_r()
available_r <- function(){

  temp <- new.env(parent = emptyenv())

  data(list = "r_nix_revs",
       package = "rix",
       envir = temp)

  get("r_nix_revs", envir = temp)

  r_nix_revs$version

}


#' rix Build a reproducible development environment definition
#' @return Nothing, this function only has the side-effect of writing a file
#'   called "default.nix" in the working directory. This file contains the
#'   instructions to build a reproducible environment using the Nix package
#'   manager.
#' @param r_ver Character. The required R version. Leave this argument empty if
#'   you want to use the latest R version available. You can check which R
#'   versions are available using `available_r`
#' @param pkgs Vector of characters. List the required packages for your
#'   analysis here.
#' @param rstudio Logical, defaults to FALSE. If TRUE, RStudio gets installed in
#'   this environment to enable interactive work.
#' @param path Character. Where to write `default.nix`.
#' @details This function will write a `default.nix` in the chosen path. Using
#'   the Nix package manager, it is then possible to build a reproducible
#'   development environment using the `nix-build` command in the path. This
#'   environment will contain the chosen version of R and packages, and will not
#'   interfere with any other installed version (via Nix or not) on your
#'   machine. Every dependency, including both R package dependencies but also
#'   system dependencies like compilers will get installed as well in that
#'   environment. If you use RStudio for interactive work, then set the
#'   `rstudio` parameter to `TRUE`. If you use another IDE (for example Emacs or
#'   Visual Studio Code), you do not need to add it to the `default.nix` file,
#'   you can simply use the version that is installed on your computer. To use
#'   Visual Studio Code however, you need to install the `{languageserver}`
#'   package, so don't forget to add it to the list of packages. Once you built
#'   the environment using `nix-build`, you can drop into an interactive session
#'   using `nix-shell`. See the "How-to Nix" vignette for more details.
#' @export
rix <- function(r_ver, pkgs, rstudio = FALSE, path = "."){
  nixTemplate <- "
    { pkgs ? import (fetchTarball 'https://github.com/NixOS/nixpkgs/archive/RE_VERSION.tar.gz') {} }:

      with pkgs;

      let
      my-r = rWrapper.override {
        packages = with rPackages; [PACKAGE_LIST];
      };
USE_RSTUDIO  my-rstudio = rstudioWrapper.override {
USE_RSTUDIO    packages = with rPackages; [PACKAGE_LIST];
USE_RSTUDIO};
      in
      mkShell {
        buildInputs = [
          my-r
         USE_RSTUDIO my-rstudio
          ];
      }"

  nixFile <- gsub('RE_VERSION', find_rev(r_ver) , nixTemplate)
  packages <- paste(pkgs, collapse = ' ')
  nixFile <- gsub('PACKAGE_LIST', packages, nixFile)
  nixFile <- gsub('USE_RSTUDIO', ifelse(rstudio, '', '#'), nixFile)

 writeLines(nixFile, normalizePath(paste0(path, "/default.nix")))
}

