# WARNING - Generated by {fusen} from dev/build_envs.Rmd: do not edit by hand

#' find_rev Find the right Nix revision
#' @param r_version Character. R version to look for, for example, "4.2.0"
#' @return A character. The Nix revision to use
#' @export
#'
#' @examples
#' find_rev("4.2.0")
find_rev <- function(r_version){

  if(r_version == "current"){
    return(get_current())
  } else {

  temp <- new.env(parent = emptyenv())

  data(list = "r_nix_revs",
       package = "rix",
       envir = temp)

  get("r_nix_revs", envir = temp)

  output <- r_nix_revs$revision[r_nix_revs$version == r_version]

  stopifnot("Error: the provided R version is likely wrong. Please check that you provided a correct R version. You can list available versions using `available_r()`" = !identical(character(0), output))

    output
}

}


#' available_r List available R versions
#' @return A character vector containing the available R versrions.
#' @export
#'
#' @examples
#' available_r()
available_r <- function(){

  temp <- new.env(parent = emptyenv())

  data(list = "r_nix_revs",
       package = "rix",
       envir = temp)

  get("r_nix_revs", envir = temp)

  c("current", r_nix_revs$version)

}


#' get_current Get the current R version and packages
#' @return A character. The commit hash of the latest nixpkgs-unstable revision
#' @importFrom httr content GET stop_for_status
#' @importFrom jsonlite fromJSON
#' @export
#'
get_current <- function() {
  api_url <- "https://api.github.com/repos/NixOS/nixpkgs/commits?sha=nixpkgs-unstable"

  tryCatch({
    response <- httr::GET(url = api_url)
    httr::stop_for_status(response)
    commit_data <- jsonlite::fromJSON(httr::content(response, "text"))
    latest_commit <- commit_data$sha[1]
    return(latest_commit)
  }, error = function(e) {
    cat("Error:", e$message, "\n")
    return(NULL)
  })
}

#' rix Build a reproducible development environment definition
#' @return Nothing, this function only has the side-effect of writing a file
#'   called "default.nix" in the working directory. This file contains the
#'   instructions to build a reproducible environment using the Nix package
#'   manager.
#' @param r_ver Character, defaults to "current". The required R version. To use the current version
#'   of R, use "current". You can check which R versions are available using `available_r`.
#' @param r_pkgs Vector of characters. List the required R packages for your
#'   analysis here.
#' @param other_pkgs Vector of characters. List further software you wish to install that
#'   are not R packages.
#' @param ide Character, defaults to "other". If you wish to use RStudio to work
#'   interactively use "rstudio", "code" for Visual Studio Code. For other editors,
#'   use "other". This has been tested with RStudio, VS Code and Emacs. If other
#'   editors don't work, please open an issue.
#' @param path Character, defaults to the current working directory. Where to write 
#'   `default.nix`, for example "/home/path/to/project".
#'   The file will thus be written to "/home/path/to/project/default.nix".     
#' @param overwrite Logical, defaults to FALSE. If TRUE, overwrite the `default.nix`
#'   file in the specified path.
#' @details This function will write a `default.nix` in the chosen path. Using
#'   the Nix package manager, it is then possible to build a reproducible
#'   development environment using the `nix-build` command in the path. This
#'   environment will contain the chosen version of R and packages, and will not
#'   interfere with any other installed version (via Nix or not) on your
#'   machine. Every dependency, including both R package dependencies but also
#'   system dependencies like compilers will get installed as well in that
#'   environment. If you use RStudio for interactive work, then set the
#'   `rstudio` parameter to `TRUE`. If you use another IDE (for example Emacs or
#'   Visual Studio Code), you do not need to add it to the `default.nix` file,
#'   you can simply use the version that is installed on your computer. To use
#'   Visual Studio Code however, you need to install the `{languageserver}`
#'   package, so don't forget to add it to the list of packages. Once you built
#'   the environment using `nix-build`, you can drop into an interactive session
#'   using `nix-shell`. See the "How-to Nix" vignette for more details.
#' @export
rix <- function(r_ver = "current",
                r_pkgs,
                other_pkgs = NULL,
                ide = "other",
                path = ".",
                overwrite = FALSE){

  stopifnot("'ide' has to be one of 'other', 'rstudio' or 'code'" = (ide %in% c("other", "rstudio", "code")))

  path <- if(path == "."){
     "default.nix"
  } else {
    paste0(path, "/default.nix")
  }

  path <- file.path(path)

  pkgs <- if(ide == "code"){
            c(r_pkgs, "languageserver")
          } else {
            r_pkgs
          }

  r_packages <- paste(r_pkgs, collapse = ' ')
  other_packages <- paste(other_pkgs, collapse = ' ')

  nixTemplate <- "
# This file was generated by the {rix} R package on DATE
# It uses nixpkgs' revision RE_VERSION for reproducibility purposes
# Report any issues to https://github.com/b-rodrigues/rix
    { pkgs ? import (fetchTarball \"https://github.com/NixOS/nixpkgs/archive/RE_VERSION.tar.gz\") {} }:

      with pkgs;

      let
      my-r = rWrapper.override {
        packages = with rPackages; [PACKAGE_LIST];
      };
OTHER_PACKAGES other-pkgs = [OTHER_PKGS];
USE_RSTUDIO  my-rstudio = rstudioWrapper.override {
USE_RSTUDIO    packages = with rPackages; [PACKAGE_LIST];
USE_RSTUDIO};
      in
      mkShell {
        buildInputs = [
          my-r
         USE_RSTUDIO my-rstudio
         OTHER_PACKAGES other-pkgs
          ];
      }"

  nixFile <- gsub('RE_VERSION', find_rev(r_ver) , nixTemplate)
  r_packages <- gsub('\\.', '_', r_packages)
  nixFile <- gsub('PACKAGE_LIST', r_packages, nixFile)
  nixFile <- gsub('OTHER_PKGS', other_packages, nixFile)
  nixFile <- gsub('OTHER_PACKAGES', ifelse(!is.null(other_pkgs), '', '#'), nixFile)
  nixFile <- gsub('DATE', date(), nixFile)
  nixFile <- gsub('USE_RSTUDIO', ifelse(!is.null(ide) & ide == "rstudio", '', '#'), nixFile)

  if(!file.exists(path) | overwrite){
    writeLines(nixFile, path)
  } else {
    stop(paste0("File exists at ", path, ". Set `overwrite == TRUE` to overwrite."))
  }

}

