# WARNING - Generated by {fusen} from dev/cicd.Rmd: do not edit by hand

#' nix_github_actions
#' @return Nothing, copies file to a diretory.
#'
#' @noRd
nix_github_actions <- function(){
  path <- file.path(".github", "workflows")
  dir.create(path)
  source <- system.file(
    file.path("extdata", "run-pipeline.yaml"),
    package = "rix",
    mustWork = TRUE
  )
  file.copy(source, path, overwrite = TRUE)
  invisible()
}
