# WARNING - Generated by {fusen} from dev/flat_cicd.Rmd: do not edit by hand

#' tar_nix_ga Run a {targets} pipeline on Github Actions.
#' @details This function puts a `.yaml` file inside the `.github/workflows/`
#' folders on the root of your project. This workflow file will use the
#' projects `default.nix` file to generate the development environment on
#' Github Actions and will then run the projects {targets} pipeline. Make
#' sure to give read and write permissions to the Github Actions bot.
#' @return Nothing, copies file to a diretory.
#' @export
tar_nix_ga <- function(){
  # Add an empty .gitignore file if there isn’t any

  if(file.exists(".gitignore")){
    NULL
  } else {
    file.create(".gitignore")
  }

  path <- ".github/workflows"

  dir.create(path, recursive = TRUE)
  source <- system.file(
    file.path("extdata", "run-pipeline.yaml"),
    package = "rix",
    mustWork = TRUE
  )
  file.copy(source, path, overwrite = TRUE)
  invisible()
}
