# Run test suite on system without Nix
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test_rix-no-nix

permissions:
  contents: read

jobs:
  devtools:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual")'
          error-on: '"warning"'

