# This file was generated by the {rix} R package v0.11.0 on 2024-09-18
# with following call:
# >rix(r_ver = "658e7223191d2598641d50ee4e898126768fe847",
#  > r_pkgs = NULL,
#  > system_pkgs = NULL,
#  > git_pkgs = list(list(package_name = "aniMotum",
#  > repo_url = "https://github.com/ianjonsen/aniMotum/",
#  > branch_name = "master",
#  > commit = "00d1c778c6cae78c46c1c5a4016512ea44654565"),
#  > list(package_name = "ggmagnify",
#  > repo_url = "https://github.com/hughjonesd/ggmagnify/",
#  > branch_name = "master",
#  > commit = "602d42d150a0b1e0895c36b9c6c8c2f56402e116")),
#  > ide = "other",
#  > project_path = "_test",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision 658e7223191d2598641d50ee4e898126768fe847 for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/658e7223191d2598641d50ee4e898126768fe847.tar.gz") {};
  
  git_archive_pkgs = [
    (pkgs.rPackages.buildRPackage {
      name = "aniMotum";
      src = pkgs.fetchgit {
        url = "https://github.com/ianjonsen/aniMotum/";
        rev = "00d1c778c6cae78c46c1c5a4016512ea44654565";
        sha256 = "sha256-V5UioRRyjj6qmT8/dSYSpv5fNLw4Ov+NtEfcRmeodcg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          tibble
          ggplot2
          TMB
          sf
          tidyr
          dplyr
          patchwork
          CircStats
          mvtnorm
          tmvtnorm
          rnaturalearth
          traipse
          terra
          trip
          RcppEigen;
      };
    })


    (pkgs.rPackages.buildRPackage {
      name = "ggmagnify";
      src = pkgs.fetchgit {
        url = "https://github.com/hughjonesd/ggmagnify/";
        rev = "602d42d150a0b1e0895c36b9c6c8c2f56402e116";
        sha256 = "sha256-w5g6J+RDpBYVir20791Zm2LLBXPLjNopqri3/lnc04A=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          ggplot2
          gridExtra
          gridGeometry
          rlang;
      };
    })
   ];
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ git_archive_pkgs   system_packages   ];
  
}
